[package]
name = "wxbeacon2http_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.10"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }